//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GridCheckboxHelperMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GridCheckboxHelperMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Windows.Core.Localization.GridCheckboxHelperMessages", typeof(GridCheckboxHelperMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle deselektieren.
        /// </summary>
        internal static string AlleDeselektieren {
            get {
                return ResourceManager.GetString("AlleDeselektieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle selektieren.
        /// </summary>
        internal static string AlleSelektieren {
            get {
                return ResourceManager.GetString("AlleSelektieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswahl umkehren.
        /// </summary>
        internal static string AuswahlUmkehren {
            get {
                return ResourceManager.GetString("AuswahlUmkehren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppe zur Auswahl zufügen.
        /// </summary>
        internal static string GruppeZurAuswahlZufügen {
            get {
                return ResourceManager.GetString("GruppeZurAuswahlZufügen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nur diese Gruppe auswählen.
        /// </summary>
        internal static string NurDieseGruppeAuswählen {
            get {
                return ResourceManager.GetString("NurDieseGruppeAuswählen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Satz ausgewählt..
        /// </summary>
        internal static string X0SatzAusgewählt {
            get {
                return ResourceManager.GetString("X0SatzAusgewählt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Sätze ausgewählt..
        /// </summary>
        internal static string X0SätzeAusgewählt {
            get {
                return ResourceManager.GetString("X0SätzeAusgewählt", resourceCulture);
            }
        }
    }
}
