//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelperRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelperRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Windows.Core.Localization.HelperRes", typeof(HelperRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Export Info.
        /// </summary>
        internal static string ExcelExport {
            get {
                return ResourceManager.GetString("ExcelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergebnismenge zu gross für Excel!.
        /// </summary>
        internal static string ExcelExportTooManyData {
            get {
                return ResourceManager.GetString("ExcelExportTooManyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrobat Files|*.pdf.
        /// </summary>
        internal static string ExportTypePdf {
            get {
                return ResourceManager.GetString("ExportTypePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Files|*.doc|Alle|*.*.
        /// </summary>
        internal static string ExportTypeRtf {
            get {
                return ResourceManager.GetString("ExportTypeRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files|*.txt|Alle|*.*.
        /// </summary>
        internal static string ExportTypeTxt {
            get {
                return ResourceManager.GetString("ExportTypeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Files (XLS, bis Office 2003)|*.xls.
        /// </summary>
        internal static string ExportTypeXls {
            get {
                return ResourceManager.GetString("ExportTypeXls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Files (XLSX)|*.xlsx.
        /// </summary>
        internal static string ExportTypeXlsx {
            get {
                return ResourceManager.GetString("ExportTypeXlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei [{0}] ist schon geöffnet oder kann nicht gefunden werden..
        /// </summary>
        internal static string FileAlreadyOpen {
            get {
                return ResourceManager.GetString("FileAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei Export.
        /// </summary>
        internal static string FileExport {
            get {
                return ResourceManager.GetString("FileExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Dateiname [{0}] ist ungültig..
        /// </summary>
        internal static string FileNameInvalid {
            get {
                return ResourceManager.GetString("FileNameInvalid", resourceCulture);
            }
        }
    }
}
