//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SaveManagerMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SaveManagerMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Windows.Core.Localization.SaveManagerMessages", typeof(SaveManagerMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Bearbeiten und Speichern des Objektes ist nicht erlaubt..
        /// </summary>
        internal static string AllowEditFalse {
            get {
                return ResourceManager.GetString("AllowEditFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein anderer Anwender bearbeitet derzeit die gleichen Daten.
        ///Das Speichern der Daten ist deshalb nicht möglich..
        /// </summary>
        internal static string AnotherUserHasChangedData {
            get {
                return ResourceManager.GetString("AnotherUserHasChangedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gleichzeitige Datenänderung.
        /// </summary>
        internal static string AnotherUserHasChangedDataCaption {
            get {
                return ResourceManager.GetString("AnotherUserHasChangedDataCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Daten konnten nicht gespeichert werden.
        ///Bitte überprüfen Sie Ihre Eingaben..
        /// </summary>
        internal static string DataNotSaved {
            get {
                return ResourceManager.GetString("DataNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte Eingaben prüfen.
        /// </summary>
        internal static string DataNotSavedCaption {
            get {
                return ResourceManager.GetString("DataNotSavedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Datensatz existiert nicht mehr..
        /// </summary>
        internal static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben nicht das Recht zu Speichern. Bitte kontaktieren Sie den Administrator des Systems..
        /// </summary>
        internal static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speicher- oder Löschoperation nicht erlaubt.
        /// </summary>
        internal static string OperationNowAllowed {
            get {
                return ResourceManager.GetString("OperationNowAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern/Löschen nicht erlaubt.
        /// </summary>
        internal static string OperationNowAllowedCaption {
            get {
                return ResourceManager.GetString("OperationNowAllowedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Speichern der Daten.
        /// </summary>
        internal static string SaveException {
            get {
                return ResourceManager.GetString("SaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern deaktiviert.
        /// </summary>
        internal static string SaveManagerDisabled {
            get {
                return ResourceManager.GetString("SaveManagerDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Speichern ist deaktiviert..
        /// </summary>
        internal static string SaveManagerDisabledCaption {
            get {
                return ResourceManager.GetString("SaveManagerDisabledCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Speichern der Daten ist nicht erlaubt, der Status lässt dieses nicht zu..
        /// </summary>
        internal static string SaveNotAllowedInvalidState {
            get {
                return ResourceManager.GetString("SaveNotAllowedInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten werden gespeichert ....
        /// </summary>
        internal static string SavingData {
            get {
                return ResourceManager.GetString("SavingData", resourceCulture);
            }
        }
    }
}
