//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuLiNet.Business.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FromToDate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FromToDate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhuLiNet.Business.Common.Localization.FromToDate", typeof(FromToDate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gültig bis Datum {0} darf nicht kleiner als gültig ab Datum {1} sein.
        /// </summary>
        internal static string DateToIsBeforeFrom {
            get {
                return ResourceManager.GetString("DateToIsBeforeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gültig ab Datum.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gültig ab Datum existiert bereits.
        /// </summary>
        internal static string FromDateAlreadyExists {
            get {
                return ResourceManager.GetString("FromDateAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gültig ab Datum darf nicht mehr verändert werden.
        /// </summary>
        internal static string FromDateFrozen {
            get {
                return ResourceManager.GetString("FromDateFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gültig ab Datum muss in der Zukunft liegen.
        /// </summary>
        internal static string FromDateFuture {
            get {
                return ResourceManager.GetString("FromDateFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target ist nicht vom Typ Csla.BusinessBase&lt;C&gt;.
        /// </summary>
        internal static string NichtCslaBusinessBase {
            get {
                return ResourceManager.GetString("NichtCslaBusinessBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.Parent ist nicht vom Typ BusinessBindingListBase&lt;L, C&gt;.
        /// </summary>
        internal static string NichtCslaBusinessBindingListBase {
            get {
                return ResourceManager.GetString("NichtCslaBusinessBindingListBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target ist nicht vom Typ ITimePeriod.
        /// </summary>
        internal static string NichtITimePeriod {
            get {
                return ResourceManager.GetString("NichtITimePeriod", resourceCulture);
            }
        }
    }
}
