//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuLiNet.Business.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MoneyRules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MoneyRules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhuLiNet.Business.Common.Localization.MoneyRules", typeof(MoneyRules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} muss grösser sein als {1}.
        /// </summary>
        internal static string MoneyGreaterThanOtherMoney {
            get {
                return ResourceManager.GetString("MoneyGreaterThanOtherMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} muss kleiner sein als {1}.
        /// </summary>
        internal static string MoneyLessThanOtherMoney {
            get {
                return ResourceManager.GetString("MoneyLessThanOtherMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert muss kleiner oder gleich {0} sein.
        /// </summary>
        internal static string MoneyMaxValue {
            get {
                return ResourceManager.GetString("MoneyMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert muss grösser oder gleich {0} sein.
        /// </summary>
        internal static string MoneyMinValue {
            get {
                return ResourceManager.GetString("MoneyMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der {0} darf nicht negativ sein..
        /// </summary>
        internal static string MoneyNotNegative {
            get {
                return ResourceManager.GetString("MoneyNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der {0} muss auf 5 Rappen gerundet werden.
        /// </summary>
        internal static string MoneyNotPayable {
            get {
                return ResourceManager.GetString("MoneyNotPayable", resourceCulture);
            }
        }
    }
}
