//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuLiNet.Business.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhuLiNet.Business.Common.Localization.ResourcesValidation", typeof(ResourcesValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} darf nicht grösser als {1} Kilobyte sein.
        /// </summary>
        internal static string ByteArrayMaxSize {
            get {
                return ResourceManager.GetString("ByteArrayMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} nur im aktuellen Jahr erlaubt.
        /// </summary>
        internal static string DateTimeCurrentYear {
            get {
                return ResourceManager.GetString("DateTimeCurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} nur in Zukunft erlaubt.
        /// </summary>
        internal static string DateTimeFuture {
            get {
                return ResourceManager.GetString("DateTimeFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} nur in erst in {1} Tagen erlaubt.
        /// </summary>
        internal static string DateTimeFutureNumOfDays {
            get {
                return ResourceManager.GetString("DateTimeFutureNumOfDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der {0} {1} ist ein Samstag.
        /// </summary>
        internal static string DateTimeNoSaturday {
            get {
                return ResourceManager.GetString("DateTimeNoSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der {0} {1} ist ein Sonntag.
        /// </summary>
        internal static string DateTimeNoSunday {
            get {
                return ResourceManager.GetString("DateTimeNoSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Datum {0} {1} liegt in der Vergangenheit.
        /// </summary>
        internal static string DateTimeTodayOrFuture {
            get {
                return ResourceManager.GetString("DateTimeTodayOrFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert muss kleiner oder gleich {0} sein.
        /// </summary>
        internal static string DecimalMaxValue {
            get {
                return ResourceManager.GetString("DecimalMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert muss grösser oder gleich {0} sein.
        /// </summary>
        internal static string DecimalMinValue {
            get {
                return ResourceManager.GetString("DecimalMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} muss kleiner sein als {1}.
        /// </summary>
        internal static string IntegerLessThanOtherInteger {
            get {
                return ResourceManager.GetString("IntegerLessThanOtherInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert muss kleiner oder gleich {0} sein.
        /// </summary>
        internal static string IntegerMaxValue {
            get {
                return ResourceManager.GetString("IntegerMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert muss grösser oder gleich {0} sein.
        /// </summary>
        internal static string IntegerMinValue {
            get {
                return ResourceManager.GetString("IntegerMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} erforderlich.
        /// </summary>
        internal static string ObjectRequiredRule {
            get {
                return ResourceManager.GetString("ObjectRequiredRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn &apos;{1}&apos; gesetzt ist muss auch &apos;{0}&apos; gesetzt werden..
        /// </summary>
        internal static string PropertyXCantBeEmptyIfPropertyYHasValue {
            get {
                return ResourceManager.GetString("PropertyXCantBeEmptyIfPropertyYHasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} darf keines der folgenden Zeichen enthalten: {1}.
        /// </summary>
        internal static string StringContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("StringContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} darf keine Leerzeichen enthalten.
        /// </summary>
        internal static string StringHasBlanks {
            get {
                return ResourceManager.GetString("StringHasBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} darf nur kleine Buchstaben enthalten.
        /// </summary>
        internal static string StringLowerCase {
            get {
                return ResourceManager.GetString("StringLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Zeilen im {0} dürfen nicht mehr als {1} Zeichen haben.
        /// </summary>
        internal static string StringMaxCharsPerLine {
            get {
                return ResourceManager.GetString("StringMaxCharsPerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kann nicht mehr als {1} Zeilen haben.
        /// </summary>
        internal static string StringMaxLines {
            get {
                return ResourceManager.GetString("StringMaxLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} darf nur grosse Buchstaben enthalten.
        /// </summary>
        internal static string StringUpperCase {
            get {
                return ResourceManager.GetString("StringUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is nicht gültig.
        /// </summary>
        internal static string StringValidation {
            get {
                return ResourceManager.GetString("StringValidation", resourceCulture);
            }
        }
    }
}
